apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: calculatedconfigmaps.k8s.haeger.de
spec:
  scope: Namespaced
  group: k8s.haeger.de
  names:
    kind: CalculatedConfigMap
    plural: calculatedconfigmaps
    singular: calculatedconfigmap
    shortNames:
      - ccms
      - ccm
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - context
                - template
              properties:
                context:
                  type: object
                  additionalProperties:
                    type: object
                    properties:
                      type:
                        type: string
                        enum: [string, json]
                        default: string
                      arg:
                        type: string
                      var:
                        type: string
                template:
                  type: object
                  required:
                    - jsonnet
                  properties:
                    jsonnet:
                      type: string
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
